### ISSUE TITLE
Issue with Train Categorizers

### ISSUE THREAD

**Issue by dylankimnguyen** [umyelab/LabGym#135]
Hi, I am currently at the step after pressing the button "Train the Categorizer", I have this error it seems, does it need to be fixed for me to proceed? When I check the "Select a Categorizer to test", it seems that the categorizer I created is there, however I did not get a "training report". I have attached the images below.

Another Question: As I am using labgym for the first time, can I create a project where I only use one animal for one behaviour?

<img width="1694" alt="Screenshot 2024-04-05 at 2 16 15 am" src="https://github.com/umyelab/LabGym/assets/109999640/14898435-fa01-4fec-888b-e1043dfd8a80">
<img width="1186" alt="Screenshot 2024-04-05 at 2 18 53 am" src="https://github.com/umyelab/LabGym/assets/109999640/fd8c0da2-ebd2-4772-bde9-187c4bb38f70">

**Comment by yujiahu415** [comment]
You need at least two categories of behaviors to start.
