### ISSUE TITLE
Issue with STD for motionless pixels

### ISSUE THREAD

**Issue by dylankimnguyen** [umyelab/LabGym#136]
It asks me to enter a value as below, what value would this be? I do not understand.
<img width="418" alt="Screenshot 2024-04-05 at 3 15 37 am" src="https://github.com/umyelab/LabGym/assets/109999640/30f00b0e-db95-460a-9260-10d872e0afa9">

**Comment by yujiahu415** [comment]
This value indicates how many details (like limb contours) to be included in the "pattern images". Higher value, less details will be included. You can test different values and compare the behavior examples generated to get an idea how it works.
