### ISSUE TITLE
Exporting a detector

### ISSUE THREAD

**Issue by apenemo** [umyelab/LabGym#145]
Hi 

I will soonely l have to use a new virtual machine. I have already trained a detector on my actual one and started generating behavior examples. 

If it is possible, how can I export the detector from my actual machine to my next one ? 

Thanks a lot

**Comment by yujiahu415** [comment]
Hi,

Yes, you can export the Detector.

First, use `pip show LabGym` to find where LabGym is installed in your computer.

Then, go the LabGym folder, find the subfolder called "detectors". All the trained Detectors are stored there. You can copy / paste a trained Detector to another computer / LabGym / detectors, and it will appear in the Detector list in the GUI of that computer.

**Comment by apenemo** [comment]
It worked perfectly fine, thanks a lot Yujia !
