### ISSUE TITLE
Recent detectron2 commit broke LabGym

### ISSUE THREAD

**Issue by vincent-legoll** [umyelab/LabGym#147]
`AttributeError: module 'torch' has no attribute 'compiler'`

As a workaround, you can take the code from just before [the commit](https://github.com/facebookresearch/detectron2/commit/181aae36820af025eed1e33e58390f7ed9261e1a) that broke it:
`pip install 'git+https://github.com/facebookresearch/detectron2.git@a59f05630a8f205756064244bf5beb8661f96180'`

Upstream issue is [here](https://github.com/facebookresearch/detectron2/issues/5268)

This is not really an issue in LabGym, but as I stumbled upon it, I thought it might help to mention it...

Feel free to close if it's inapropriate.

**Comment by vincent-legoll** [comment]
Or maybe change the installation doc to use the following, which should work:
`pip install 'git+https://github.com/facebookresearch/detectron2.git@v0.6'`

I have not tested this incantation though.

**Comment by yujiahu415** [comment]
Thank you so much for pointing out this! Yes, we’ll update the installation instructions to reflect that issue! By the way, can you also let me know which PyTorch version you used when having this issue? I checked the PyTorch and this attribute error seemed to exist before torch<2.0. Not sure whether 2.0.1 still had this error. Thanks!

**Comment by vincent-legoll** [comment]
I checked today, that's what I have, but I cannot remember if this was the one at time of failure:
```
(venv-labgym) labgym@labgym:~$ pip list|grep -i torch
torch                        2.0.1+cu118
torchvision                  0.15.2+cu118
```

**Comment by yujiahu415** [comment]
Thanks for letting me this! Looks like the issue also exists with torch2.0.1.
