### ISSUE TITLE
Errors while installing LabGym

### ISSUE THREAD

**Issue by eunjoy21** [umyelab/LabGym#153]
Hi, 

Even after installing all including, Git, Visual Studio C++ build tools, pipx, and detectron, LabGym cannot be open. Could you look into my prompt and help me out? 

Thank you!

(base) C:\Users\eunjo>python --version
Python 3.11.7

(base) C:\Users\eunjo>pipx --version
1.5.0

(base) C:\Users\eunjo>pipx inject --index-url https://download.pytorch.org/whl/cu118 LabGym torch==2.0.1 torchvision==0.15.2
  injected package torch into venv labgym
done! ✨ 🌟 ✨
  injected package torchvision into venv labgym
done! ✨ 🌟 ✨

Installing collected packages: detectron2
  Attempting uninstall: detectron2
    Found existing installation: detectron2 0.6
    Uninstalling detectron2-0.6:
      Successfully uninstalled detectron2-0.6
  Running setup.py develop for detectron2
Successfully installed detectron2-0.6

(base) C:\Users\eunjo>pipx reinstall LabGym --python 3.11
⚠️ No executable for the provided Python version '3.11' found in py launcher. Please make sure the
    provided version is listed when running `py --list`.

(base) C:\Users\eunjo>pipx reinstall LabGym --python
usage: pipx reinstall [-h] [--quiet] [--verbose] [--python PYTHON] [--fetch-missing-python] package
pipx reinstall: error: argument --python: expected one argument

(base) C:\Users\eunjo>pipx reinstall LabGym --python 3.11.7
⚠️ No executable for the provided Python version '3.11.7' found in py launcher. Please make sure the
    provided version is listed when running `py --list`.

(base) C:\Users\eunjo>LabGym
'LabGym' is not recognized as an internal or external command,
operable program or batch file.

**Comment by yujiahu415** [comment]
Hi,

First, we have only thoroughly tested LabGym on python3.9 and 3.10. So we recommended using python3.9 or 3.10.

Second, why do you need reinstall LabGym? Can you make sure LabGym is installed successfully? You can follow the steps in the installation instructions: https://labgym.readthedocs.io/en/stable/installation/windows.html. And let me know if it still doesn't work.

**Comment by eunjoy21** [comment]
Hi Yujia,

Thank you so much for your prompt response!
After installing Python 3.10, everything worked! Thanks a lot!

Best,
Eunjoo

**Comment by yujiahu415** [comment]
Thanks for letting me know this!
