### ISSUE TITLE
Issue with test detectors

### ISSUE THREAD

**Issue by MCR3312** [umyelab/LabGym#154]
<img width="851" alt="image" src="https://github.com/umyelab/LabGym/assets/169915538/2f7c7d18-2644-4dd1-905c-e70580ff4d1d">

Hello, I made all the installation as indicated on the page, also I made the annotation of the images using the recommended tool roboflow, however at the time of making the train detectors I get this error and I have not been able to solve it, I hope you can please help me.

**Comment by yujiahu415** [comment]
Hi,
This error indicated that the detectron2 was not installed. You can follow the installation instructions to install detectron2: https://labgym.readthedocs.io/en/stable/installation/windows.html

**Comment by ResInAB** [comment]
I'm having issues with training detectors but obtaining the following error:
AttributeError: Cannot find field 'gt_masks' in the given Instances

Is this also a detectron2 installation issue?

**Comment by yujiahu415** [comment]
It’s possible a detectron2 issue. I have never seen this error before. You probably can follow the suggestion in this issue https://github.com/umyelab/LabGym/issues/147 to make sure you install the right version of detectron2. And let me know whether the issue is addressed.

**Comment by MCR3312** [comment]
Hi, I already download the detectron2, however the Program does not recognize it. May could be the versión of the detectron2 that i´m charging the one that isnt correct?

**Comment by yujiahu415** [comment]
Hi,
Can you paste the screenshot of your terminal? I would like to see what indicates that the detectron2 was not recognized.

**Comment by ResInAB** [comment]
> It’s possible a detectron2 issue. I have never seen this error before. You probably can follow the suggestion in this issue #147 to make sure you install the right version of detectron2. And let me know whether the issue is addressed.

I followed the suggestion in issue #147 but I received the same error as before.

This is what shows after running 
pip install git+https://github.com/facebookresearch/detectron2.git@a59f05630a8f205756064244bf5beb8661f96180
in command prompt:
![image](https://github.com/umyelab/LabGym/assets/169934751/504f2705-3331-4f42-befd-9421ccf969d8)

**Comment by yujiahu415** [comment]
Hi @ResInAB,
Can you let me know how you did the Detector training, like how you annotated the training images? For example, what type of project did you select when creating the dataset? And what format did you select when exporting the annotated dataset? When you train the Detector, what settings did you specify?
Thanks!

**Comment by ResInAB** [comment]
Hello yujiahu415,

I created an object detection project on roboflow with 2 classes.  The format I selected was 'COCO' under the JSON header.  The preprocessing settings applied were auto orient, static crop, and resize 640x640.
I also created a 2nd version with augmentation applied: Flip(horizontal), 90 degree rotate, 15% grayscale.

Thank you

**Comment by yujiahu415** [comment]
Hi,
You need to choose “instance segmentation” as project type and when exporting datasets, choose “coco segmentation” format. You can just create a new project and upload all your annotated images and specify the correct settings and export it again.

**Comment by yujiahu415** [comment]
Hi,
Your terminal indicates that the training was successfully initiated. Does your computer have a GPU? We recommend using a decent GPU for Detector training. If it was just stuck there for a long time, that means the computing capacity of your GPU isn’t sufficient to achieve good speed.

**Comment by ResInAB** [comment]
Understood.  Thank you.  
Will a message be displayed in Command Prompt when training is completed?

**Comment by yujiahu415** [comment]
Yes. There will be a "Detector training completed." message after the training is done.
