### ISSUE TITLE
New error : line 5: 2686631 Killed                  LabGym

### ISSUE THREAD

**Issue by apenemo** [umyelab/LabGym#156]
Hi

I faced this error while trainning a categorizer with augmented data  :/data/labgym/bin/labgym: line 5: 2686631 Killed                  LabGym
 
I have not face it while training categorizers without augmenting data. Do you think this could be the problem or does it come from somewhere else ? 

Many thanks !

**Comment by yujiahu415** [comment]
Hi,
This is simply because your computer system run out of memory. You can select less augmentation methods to reduce the memory consumption, if adding more memory to your system is not feasible.

**Comment by vincent-legoll** [comment]
@yujiahu415 are we speaking of main system RAM, or GPU/VRAM ? The first one can be increased, but not the GPU's...

The GPU card used by @apenemo is : nvidia Tesla T4 with 16GB VRAM
