### ISSUE TITLE
missing data after "analyze behaviors" 

### ISSUE THREAD

**Issue by vzimmern** [umyelab/LabGym#157]
Good afternoon,

I am using "Analyze Behaviors", only obtaining animal kinematics (no categorizer). I selected 4 locomotion parameters and I'm interested in acceleration. 

In the resulting excel file, there is some missing data. Here's a screenshot. 

![image](https://github.com/umyelab/LabGym/assets/139922549/6be7e8d0-2a61-4c1a-90c5-02a83db8791b)

Is there a reason for the missing data? Anything I can do to fix that?
Thanks!

**Comment by yujiahu415** [comment]
Hi,
I guess the missing data is ‘acceleration’, right? It is calculated as (max velocity - min Velocity) / t, where Vmax and Vmin is found within a behavior episode, and t is the duration of the change from Vmax to Vmin or Vmin to Vmax. So when during a behavior episode the Vmax equals to Vmin, the t is 0 and cannot be divided. And at that frame, the data is ‘na’. You can simply replace all the missing data with ‘0’ if you want.

**Comment by yujiahu415** [comment]
Hi,
The ‘angle’ has been deprecated since v1.9 because later I realized that the calculation sometimes may not represent the true angle and thus may not be always useful. But the ‘distance’ is still there. You can choose ‘4 locomotion parameters’ and the distance will be calculated.
