### ISSUE TITLE
Could not find TensorRT

### ISSUE THREAD

**Issue by odong8322OU** [umyelab/LabGym#164]
Hi,

I am having this warning pop up whenever I load up LabGym (see screenshot below).
<img width="571" alt="Screenshot 2024-07-03 at 11 28 36 AM" src="https://github.com/umyelab/LabGym/assets/174055084/2a794e23-0b9e-48a8-9956-b43a6340c740">

It still initializes the user interface, but when I try to train the detector, it takes a long time and eventually exits with 'Killed'.
<img width="568" alt="Screenshot 2024-07-03 at 11 43 41 AM" src="https://github.com/umyelab/LabGym/assets/174055084/0af08e6f-cf0b-4df4-9125-94af21bc4a3d">

Do you know why this error occurs? Thanks!

**Comment by yujiahu415** [comment]
Which version of tensorflow did you use?
The program being killed is possibly because the GPU ran out of memory. Which NVIDIA GPU did you use and what is the VRAM?
