### ISSUE TITLE
cannot install Detectron2

### ISSUE THREAD

**Issue by mythhero2** [umyelab/LabGym#170]
After finishing installment of LabGym, tried to install Detectron2 using the below code:

python3 -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

This installation code produced below error messages:

Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /private/var/folders/sm/nq68682d2v3bz8hz211br_rm0000gn/T/pip-req-build-d4jcu9v4
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /private/var/folders/sm/nq68682d2v3bz8hz211br_rm0000gn/T/pip-req-build-d4jcu9v4
  Resolved https://github.com/facebookresearch/detectron2.git to commit 70f454304e1a38378200459dd2dbca0f0f4a5ab4
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/sm/nq68682d2v3bz8hz211br_rm0000gn/T/pip-req-build-d4jcu9v4/setup.py", line 11, in <module>
          from torch.utils.cpp_extension import CUDA_HOME, CppExtension, CUDAExtension
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Please let me know what I should do...

**Comment by yujiahu415** [comment]
Hi,
Please see this same issue for the solution:

https://github.com/umyelab/LabGym/issues/169

And let me if it works or not. Thanks!

**Comment by mythhero2** [comment]
Thanks! Now it can be installed..

**Comment by yujiahu415** [comment]
Great! Thanks for letting me know this!
