### ISSUE TITLE
Error message when starting 'Train Detectors'

### ISSUE THREAD

**Issue by mythhero2** [umyelab/LabGym#174]
After generating image examples, annotation was done via Roboflow. When trying 'Train Detectors' using the annotated images with json file, below error message was shown:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/LabGym/gui/training/detectors.py", line 398, in train_detector
    Detector(name=detector_name).train(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/LabGym/detector.py", line 168, in train
    if "LabGym_detector_train" in DatasetCatalog.list():
NameError: name 'DatasetCatalog' is not defined

What did I do wrong?

**Comment by yujiahu415** [comment]
Hi,

This error indicates that the detectron2 hasn't been successfully installed or imported. When you initiate LabGym, did you receive this warning in the terminal: 'You need to install Detectron2 to use the Detector module in LabGym...'?

It's also possible that the detectron2 may be installed in a different environment from LabGym. Can you also check this?

You can try `python3` to initiate python3 and type `import LabGym` and `import detectron2` to see if there's any importing errors.

**Comment by mythhero2** [comment]
I tried rebuild above under python 3.10.14. Everything went OK, and PyTorch downgrade was successful.

However, the error 'You need to install Detectron2 to use the Detector module in LabGym...' is still coming up after initiating LabGym, as following:

You need to install Detectron2 to use the Detector module in LabGym:
https://detectron2.readthedocs.io/en/latest/tutorials/install.html
2024-07-15 18:24:46.622 Python[59371:1660682] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
The user interface initialized!

**Comment by yujiahu415** [comment]
After rebuilding everything under python3.10.14, have you also tried to initiate python3 to check its version, and import LabGym and detectron2 to see if they were successfully installed within python3.10.14, and also check PyTorch version==2.0.1? If so, can you try to uninstall detectron2 `python3 -m pip uninstall detectron2` and then upgrade PyTorch `python3 -m pip install torch==2.3.1`, and then reinstall detectron2 `python3 -m pip install 'git+https://github.com/facebookresearch/detectron2.git'`, and then downgrade PyTorch to v2.0.1: if your system is Mac, try `python3 -m pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2`.
And let me know if this works.

**Comment by mythhero2** [comment]
As you recommended, I rebuild everything under python 3.10.14, detectron2 was reinstalled under Pytorch2.3.1. Then Pytorch2.0.1 was re-installed. 


Everything works well. My problems were the python version required for PyTorch v2.0.1 and whether detectron2 was installed in same environment.

Thanks for your advise!

**Comment by yujiahu415** [comment]
Thanks for letting me know this!
