### ISSUE TITLE
Windows train User interface does not allow analysis of images (only videos)

### ISSUE THREAD

**Issue by DiegoStH** [umyelab/LabGym#205]
When using the user interface of LabGym Analyse module, although it says that it can generate results based on images (even if it is just for motion tracking) it does not allow me to load images for analysis, as the loading window limits my file type to only videos.
Is there a workaround for this?

![image](https://github.com/user-attachments/assets/2fd5b9c7-8730-44c9-bb1c-ddd96c655716)

**Comment by yujiahu415** [comment]
Hi,

The static image mode doesn't support tracking only. So you have to choose a Categorizer that is trained with static image mode to analyze behaviors in images.
