### ISSUE TITLE
Issue concerning mouse detection during “Generate Behaviour Examples”

### ISSUE THREAD

**Issue by ThePowerHoster** [umyelab/LabGym#22]
Hello, 

I’ve been having a recurring issue during the “Generate Behaviour Examples” step of the process. While most pattern images seem accurate (they show the position of the mouse throughout the behavioural bout), some of them seem to detect not only the mouse but also a certain area of the open field in which the mouse put into for filming. The shape of the area as well as its volume always changes each time I try to re-do the step. 

This problem on its own isn’t too bad because I can simply skip over them when categorizing the behavioural examples. The real problem comes when I analyse my video (Behaviour Analysis). When watching the annotated video, I can see that areas similar to the ones explained earlier appear throughout the video. These areas are much bigger than the mouse and are wrongly picked up as a behaviour. 

I don’t see any changes in the filming condition that could possibly explain the appearance of these areas throughout the behavioural example pairs. 

If you could provide me with a contact email, I could send you examples of these areas during the “Generate Behaviour Examples” and the “Behaviour Analysis” steps

Thank you very much
![Pattern Example 1](https://user-images.githubusercontent.com/115037043/236507565-68003a0b-6102-4adf-a115-9b2550a07a6d.jpg)
![Pattern Example 2](https://user-images.githubusercontent.com/115037043/236507567-b70d6f9d-61e9-4ec4-a4af-50cb199e3c87.jpg)
![Pattern Example 3](https://user-images.githubusercontent.com/115037043/236507569-ab78996f-75c2-498f-a489-ce5c92966d8f.jpg)
![Video Example 1](https://user-images.githubusercontent.com/115037043/236507571-f7fd014e-967c-4be1-bc37-f779ca1fd6d2.png)
![Video Example 2](https://user-images.githubusercontent.com/115037043/236507574-322b11b2-5644-4b48-80b2-bf5a62da6e83.png)

**Comment by yujiahu415** [comment]
Sure! Here is my email: henryhu@umich.edu
You may send me a sample video that has this issue so that I can replicate the issue myself and see what is the cause.
