### ISSUE TITLE
Train Categorizer

### ISSUE THREAD

**Issue by svilca14** [umyelab/LabGym#232]
Hello,

I am trying to train the categorizer, and the program recognizes that there are two behaviors (jump, rear), but seems to have ran only one of them (jump). I've attached a .txt document of the code and an image of the training parameters. 

For additional background, I am using a truncated video to make sure I can run through the whole pipeline. Thank you!

<img width="737" alt="Train_Categorizer_Parameters" src="https://github.com/user-attachments/assets/239a323c-c4ed-4bcc-bc58-c9d89a74b142">

[Train_Categorizer_Issue.txt](https://github.com/user-attachments/files/17851201/Train_Categorizer_Issue.txt)

**Comment by svilca14** [comment]
Thank you! Happy the update was an easy fix. Ran correctly this time!

**Comment by yujiahu415** [comment]
Great! Thank you for letting me know this!
