### ISSUE TITLE
Customization of Detector

### ISSUE THREAD

**Issue by panyuxin1993** [umyelab/LabGym#236]
Congratulations about the wonderful tool. I noticed that Detection2 does not have a built-in Re-ID function, which may limit its power of identity tracking for videos with multiple animals. Is it possible to customize Detector of LabGym by adding a Re-ID function or incoporate other out-of-box MOT/MOTS tools? Do you have plan to do incorporate other tool for tracking or are users allowed to do that?

**Comment by yujiahu415** [comment]
Hi,

Thanks! Detectron2 doesn't have a built-in Re-ID function, but LabGym does. LabGym has a tracking algorithm that based on appearance features and centroid distances among frames. The detection outputs by the Detectron2 will go through this tracking algorithm for IDing. If the objects/animals have distinct appearance features like different body colors, you can teach LabGym Detectors to distinguish them by annotating them as different classes, like white mouse and black mouse, and they will be tracked accurately even in occlusion and disappearing / reappearing.

However, if the animals look all the same (no appearance features to distinguish them), the tracking algorithm will be purely based on centroid distances. In this scenario, you have to annotate the majority of occlusion / colliding scenarios to teach the Detector correctly segment the animals when they have close body contact and they bodies change shapes to avoid ID switching.

I have been thinking about how to improve the tracking accuracy other than increasing the annotated frames in the second scenario (multiple animals look exactly the same) but hasn't yet found an efficient way to avoid ID switching.

LabGym is open source, and its license permits you to modify its source code. So welcome to customize Detectors on your own.

**Comment by panyuxin1993** [comment]
Thank you for your very detailed response. That's very helpful!

**Comment by yujiahu415** [comment]
No problem! Just let me know if you have additional questions.
