### ISSUE TITLE
Training examples are not created 

### ISSUE THREAD

**Issue by apenemo** [umyelab/LabGym#44]
Hi 

After I have sorted the behaviours I am interested in, I want to train a categorizer. Yet when asked to create "training examples", nothing appears in the folder I choosed as a directory to store the training examples. 

What appears on my anaconda shell is : 

"Behavior names are: []
All prepared training examples stored in: C:\Users\admin-labgym\Desktop\night work\Deja trié\SH2"

Maybe I haven't named my files correctly ? As it seems that LabGym should know what the behaviour name is. 

here is what my files look like:

![image](https://github.com/umyelab/LabGym/assets/110259129/1757cf05-da6c-4ae7-9925-89960d9746ae)

Also, I tried to use the " Sort behaviours example tool", it does work as intended but only for one video. After having marked a video with the choosen shortcut, nothings works anymore not even the "next" and " previous" shortcuts. 

Best wishes

**Comment by yujiahu415** [comment]
Hi,
Can you make the names of the folder all regular English letters and try again let me know if you still have this problem? Thanks!
I’m wondering if it is caused by the unique characters like ‘é’ in the path to your files, which prevents the files being read correctly.

**Comment by apenemo** [comment]
hi, i changed the é letter and the problem remains the same 
![image](https://github.com/umyelab/LabGym/assets/110259129/81f8d46d-49ce-4cd7-a205-c5998b491a82)

**Comment by yujiahu415** [comment]
Hi,

By looking at the folder structure you showed and the information in the cmd, it seemed that all your behavior examples are directly stored in the '../all' folder, right? So where are your behavior names? LabGym needs to read the names of each folder that stores the behavior examples of each behavior type. Here is correct structure:

Suppose you have behaviors A, B, and C. You first create a parent folder, let's call it '.../all behaviors'. Then you create subfolders in the '.../all behaviors' folder: .../all behaviors/A, .../all behaviors/B, and .../all behaviors/C. Then you move behavior examples into the .../all behaviors/A, .../all behaviors/B, or .../all behaviors/C folders. Then you input the 'all behaviors' folder into the 'prepare the training example' functional unit and select an output folder (let's call it '.../training'), and click 'Start to prepare the training examples'. After that, all the prepared examples will be stored in '.../training' folder. When you train a Categorizer, directly input that '.../training' folder for training.

The above is how the sorting in LabGym works. The 'Sort behavior examples' can make this process easier but it seems not working on your pc. I will fix this in the next update. But before that, you can sort examples and create a training dataset to train a Categorizer as what I mentioned above, to see if it addresses the issue.

**Comment by apenemo** [comment]
Thanks for your quick response, I will do it right now and keep you updated as soon as possible

**Comment by apenemo** [comment]
it worked ! I have to reformat my whole dataset now but understand how to train my categorizer ! I am so happy to finally be able to work on my main project and it is most certainly thanks to your help for which I am so gratefull. 

Cheers from France ;)

**Comment by yujiahu415** [comment]
Glad to be helpful! Cheers! :)
