### ISSUE TITLE
Difficulty Training the Detector

### ISSUE THREAD

**Issue by LavanyaDhavala** [umyelab/LabGym#47]
Hi, 
I am trying to train the detectors and have the following issue 

NameError: name 'DatasetCatalog' is not defined
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/LabGym/gui_detectors.py", line 380, in train_detector
    if str('LabGym_detector_train') in DatasetCatalog.list():
                                       ^^^^^^^^^^^^^^
NameError: name 'DatasetCatalog' is not defined

I would appreciate any help troubleshooting this problem. Additionally, I was wondering if there a time length limit for which a a video can be analyzed?

**Comment by yujiahu415** [comment]
This error indicates that the Detectron2 has not been properly installed. To install Detectron2, you can type:
python3 -m pip install 'git+https://github.com/facebookresearch/detectron2.git
or
python3 -m pip install git+https://github.com/facebookresearch/detectron2.git
If you have issues in installing Detectron2, please refer to https://detectron2.readthedocs.io/en/latest/tutorials/install.html
