### ISSUE TITLE
Error in the analysis of a behavior with trained detectors and categorizer

### ISSUE THREAD

**Issue by apenemo** [umyelab/LabGym#49]
Hi Yujia, I thought I would finally stop to bother you after having successfully trained my categorizer. I was wrong ;).

After having trained both my detectors and categorizers on " not free" backgrounds samples. I face this error.

"Preparation started...
2023-07-13 13:31:49.640639
The total categories of animals / objects in this Detector: ['Fake monkey', 'Japanese-Deer', 'Japanese-Macaques', 'Tree branch']
The animals / objects of interest in this Detector: ['Japanese-Macaques']
The inferencing framesize of this Detector: 960
Video fps: 25
The original video framesize: 1080 X 1920
Prepration completed!
Acquiring information in each frame...
2023-07-13 13:31:50.859432
Traceback (most recent call last):
  File "C:\Users\admin-labgym\anaconda3\envs\detectron_env\lib\site-packages\LabGym\gui_analyzers.py", line 806, in analyze_behaviors
    AAD.acquire_information(batch_size=self.detector_batch,background_free=self.background_free)
  File "C:\Users\admin-labgym\anaconda3\envs\detectron_env\lib\site-packages\LabGym\analyzebehaviorsdetector.py", line 705, in acquire_information
    self.detect_track_individuals(batch,batch_size,frame_count_analyze,background_free=background_free,animation=animation)
  File "C:\Users\admin-labgym\anaconda3\envs\detectron_env\lib\site-packages\LabGym\analyzebehaviorsdetector.py", line 495, in detect_track_individuals
    blob=extract_blob_background(f,self.animal_contours[i][max(0,frame_count_analyze+1-batch_size+batch_count-self.length+1):frame_count_analyze+1-batch_size+batch_count+1],contour=None,channel=self.channel,background_free=False)
KeyError: 0"

I don't understand where the problems comes from. 

Thank you very much

**Comment by yujiahu415** [comment]
Hi,

This issue was caused by a bug. I have just fixed it. Please update LabGym and see if it works or not. 
And always let me know if you have any questions or issues!

**Comment by apenemo** [comment]
Hi unfortunately I do not have access to my virtual machine until monday. I'll keep you updated as soon as possible. 

thanks !

**Comment by apenemo** [comment]
it worked perfectly fine. Thank you !

**Comment by yujiahu415** [comment]
Great! Thank you for letting me know!
