### ISSUE TITLE
Distance Output Conversion

### ISSUE THREAD

**Issue by jdohn15** [umyelab/LabGym#9]
Hello, 

Our lab is trying to utilize this cool software to measure movement of leeches. I seem to have gotten a model that captures the behaviors we are interested in. I am wondering how to interpret the "distance" from the summary.xlsx the program outputs. How do I convert the distance it gave us, into something we can comprehend like mm or cm? Is the distance in pixels?

Thanks,

John

**Comment by yujiahu415** [comment]
Hi John,

The 'distance' is first calculated in pixels and then normalized to (divided by) the size of a single animal (still in pixels). So it does not have a unit (you can say it's 'normalized distance'). 

The rationale of designing it this way is that it is usually easier to control the size of the animals than to calculate the pixel / actual mm/cm ratios.

If the distance is output in pixels, users need to know the pixel / actual cm ratio in this particular video for conversion. But sometimes the pixel / actual cm ratio is difficult to precisely know. And even a little change in camera position / zoom-in level might cause a huge change in pixel-to-actual cm ratios, which can potentially make the comparisons of analysis results from different videos or videos with different recording settings difficult.

In the other hand, if the distance is normalized to the size of a single animal, as long as the size of a single animal is consistent across experiment sessions / videos, users don't need to know the pixel / actual cm ratio to compare the analysis results across different videos or videos with different recording settings. We typically use animals of the similar size for different batches (sessions) of a same experiment, right?

Let me know if my explanation answers your question. And let me know if you still want to get the 'distance' in pixels--I can do that in the next update of LabGym.

**Comment by yujiahu415** [comment]
Hi John,

The option of 'output all the distances in pixels' has now been added into the latest version 1.5. You may use the 'pip install --upgrade LabGym' to upgrade LabGym to its latest version.
