### ISSUE TITLE
Issue with Image Generation

### ISSUE THREAD

**Issue by dlala101** [umyelab/LabGym#95]
I am trying to generate new images and have been getting the following error 

[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available
[mpeg2video @ 00000206dec13f00] qscale == 0
[mpeg2video @ 00000206dec13f00] Warning MVs not available

Any help would be appreciated!

**Comment by yujiahu415** [comment]
Hi,
This issue is due to unsupported video codec. What is your video format? .mpeg? A simple solution would be converting your videos into .mp4 / .mov or .avi format.
